// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class ImagesRes {
  ImagesRes._();

  static const String PROJECT_NAME = 'maria';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String DEFAULT_WALLPAPER = 'images/chatgpt/default_wallpaper.png';
  static const String IC_GPT3TURBO = 'images/chatgpt/ic_gpt3turbo.png';
  static const String IC_GPT4 = 'images/chatgpt/ic_gpt4.png';
  static const String IC_MAIL = 'images/chatgpt/ic_mail.png';
  static const String IC_REFRESH = 'images/chatgpt/ic_refresh.png';
  static const String IC_SHARE = 'images/chatgpt/ic_share.png';
  static const String IC_SPEAK = 'images/chatgpt/ic_speak.png';
  static const String VOLUMN = 'images/chatgpt/volumn.json';
}
